name: CI & CD

on:
  push:
    tags:
      - '*'

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_RELEASE_BUILD: true
        with:
          gradle-version: 7.6
          arguments: clean test build publish --stacktrace
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Upload kgraphql Test Results
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test Results
          path: kgraphql/build/test-results/test/*.xml
          reporter: java-junit
      - name: Upload kgraphql-ktor Test Results
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test Results
          path: kgraphql-ktor/build/test-results/test/*.xml
          reporter: java-junit
